### ISSUE TITLE
Support for node 4.2.2

### ISSUE THREAD

**Issue by zeachco** [zeachco/stubborn-server#2]
I've been requested to support this version of node
CC @ruyadorno

**Comment by ruyadorno** [comment]
at node@5 only issue is the spread operator on `server/logger.js`

**Comment by zeachco** [comment]
I was thinking of exposing a `require('stubborn-server/es5')` which loads the index.js but with `babel-register` or just "fix" some of the goodies we have in es6

**Comment by ruyadorno** [comment]
Might be a good idea, I know a lot of popular node projects kept a specific previous major release around as an `es5` supported branch and kept master up to date with latest `es6` features on a bumped up major version, if I was to make that move I'd make some research to see what is already being used by popular npm packages around.

Now, to be honest, I don't think it's worth that kind of effort, if we're just looking to support the internal use at @AppDirect, we're talking about a single feature that took me 5sec to remove from the file and get the project running on node@5 - plus it shouldn't be long until the platform team updates our infrastructure to node@6 and at that point we can just revert the commit.

It's up to you to decide which solution suits you best.

**Comment by zeachco** [comment]
For now, just extended support to 4.2.2
If supporting multiple versions gets complex, I'll separate it into multiple builds
