### ISSUE TITLE
CORS Support by default

### ISSUE THREAD

**Issue by igneel64** [zeachco/stubborn-server#53]
## Feature request
(_This came from my use of the [snapstub package](https://www.npmjs.com/package/snapstub)_)
Allowing CORS support. 
Currently trying to mock some API calls in another localhost instance, the user is faced with CORS issues if the user-agent requires an OPTIONS request.
The handlings that exists currently does not seem to prevent this case:
See https://github.com/zeachco/stubborn-server/blob/c11f3d4d0f1cd5ed0270147bb8226d867231d832/server/app.js#L15-L19

## Steps to Reproduce the Problem
  1. Start a local application on a different port than the server.
  2. Request a resource that would require an OPTIONS request.
  3. CORS issue occurs
_Tested in latest Google Chrome_

## Resolution
By only the addition of the [cors middleware](https://www.npmjs.com/package/cors), the server is able to handle the OPTIONS request correctly and then move on and allow us to use this package as expected.

__If the maintainers think this is a valid request, I can create a PR as soon as possible__

**Comment by ruyadorno** [comment]
Sure thing 👍 I think it does make sense and a PR would be welcome 😄 it would be nice to also have some tests to make sure it doesn't break again in the future 😊 Thanks!
